### ISSUE TITLE
网卡绑定的不对

### ISSUE THREAD

**Issue by catna** [andrewXiaY/AutoShuttle#2]
```python
def main():

    hostname = socket.gethostname()
    ip_address = socket.gethostbyname_ex(hostname)[-1][-1]    # 这里通过hosts解析得到的是局域网卡
    ip_address = '127.0.0.1'    # 这里指定的是 loopback 回环
    port = 6060 if len(sys.argv) == 1 else int(sys.argv[1])
    # ip_address = get_ip(int(sys.argv[-1]))
```

一台主机可以有多张网卡(虚拟的或者真实的)
- 其中 loopback 回环是 `127.0.0.1`, 在MacOS上使用 `ifconfig`指令可以看到 `lo0`网卡与之对应
- 如果是局域网比如说 `192.168.0.1`这样, 那么对应的是一个以太网网卡, 如 `en0`(ethernet)
一般提供公网IP的云主机, 都会绑定2张实体网卡(不考虑虚拟化技术), 这样的话会有三个 IP, 分别是`127.0.0.1`, `192.168.0.1`(局域网IP), `41.23.xx.xx`(广域网IP); 虚拟网卡什么的不考虑

不同网卡之间的通信是要依靠系统提供的路由表来管理的. 但是默认情况下, 局域网卡的数据, 不能直接转发到广域网卡.
比如你服务进程绑定的网卡是 `172.10.xx.xx`, 访问`127.0.0.x` 并不能实现数据通信

**Comment by andrewXiaY** [comment]
哈哈，受教了！
